In [1]:
#paquetes python
import os
import numpy as np
import copy
import pprint
from math import sqrt
from scipy.linalg import solve_triangular
import inspect
import sys

#paquetes funciones definidas obtenidas de archivos .py
import funciones_factorizacion_QR as fQR

## Prueba solución incorrecta

In [2]:
#Generamos un sistema de ecuaciones lineales
m=4
n=4
A=np.round(fQR.crear_matriz_aleatoria(m,n,6,-6,False),2)
b = np.round(fQR.crear_matriz_aleatoria(m,1,6,-6,False),2)
print("A:",A)
print("b:",b)

A: [[ 3.99 -3.95  3.14  3.52]
 [-0.9  -1.44  4.25  1.15]
 [-0.28  1.22  3.13  3.54]
 [ 3.7  -4.91  0.62  5.05]]
b: [[-0.7 ]
 [-5.54]
 [-1.07]
 [ 0.4 ]]


In [3]:
np.linalg.solve(A,b)

array([[ 1.17839311],
       [ 0.8994129 ],
       [-0.80026723],
       [ 0.1885601 ]])

In [4]:
fQR.Solucion_SEL_QR_nxn(A,b)

array([[ 1.55123708],
       [ 0.96347167],
       [-0.57104714],
       [-0.1885601 ]])

In [5]:
fQR.eliminacion_bloques(A,b)

2
2


array([[-7.46923333],
       [-9.05860053],
       [ 4.37329984],
       [-3.22353605]])

## Prueba solución correcta

In [11]:
#Generamos un sistema de ecuaciones lineales
m=4
n=4
A=np.round(fQR.crear_matriz_aleatoria(m,n,6,-6,False),2)
b = np.round(fQR.crear_matriz_aleatoria(m,1,6,-6,False),2)
print("A:",A)
print("b:",b)

A: [[ 5.79  4.86  4.33  1.91]
 [-4.03  5.34 -1.56  3.1 ]
 [ 2.25 -1.45 -1.05 -4.87]
 [-1.17 -3.13 -2.51 -4.05]]
b: [[ 1.  ]
 [ 1.5 ]
 [-0.69]
 [ 2.84]]


In [12]:
np.linalg.solve(A,b)

array([[-16.23160451],
       [  3.04849526],
       [ 24.48878786],
       [-13.5451038 ]])

In [13]:
fQR.Solucion_SEL_QR_nxn(A,b)

array([[-16.23160451],
       [  3.04849526],
       [ 24.48878786],
       [-13.5451038 ]])

In [14]:
fQR.eliminacion_bloques(A,b)

2
2


array([[-16.23160451],
       [  3.04849526],
       [ 24.48878786],
       [-13.5451038 ]])