# Prueba Precisión - Factorización QR (Revisión 2)

Importamos la librerías necesarias.

In [1]:
#paquetes python
import numpy as np
import pprint

# paquetes funciones definidas obtenidas de archivos .py
import funciones_factorizacion_QR as fqr

## EJEMPLO 1 - Matriz de dimensión 5x3 (Filas > Columnas)

Verificaremos que la factorización QR de una matriz obtenida con la función de numpy, es igual a la obtenida con la función implementada por los programadores.

Empezaremos por generar una matriz aleatoria con la función crea_matriz

In [2]:
# Generamos una matriz aleatoria de tamaño definido (renglones y columnas) y valores aleatorios comprendidos en un rango, pudiendo ser sus entradas de tipo enteros o dobles
m=5
n=3
A=np.round(fqr.crear_matriz_aleatoria(m,n,6,-6,False),2)
A

array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])

### Implementación programadores

Utilizamos la función matriz_Q_R para obtener Q y R a partir de A.

In [3]:
Q , R = fqr.matriz_Q_R(A)

Visualizamos Q.

In [4]:
np.round(Q,4)

array([[-0.6149, -0.1086,  0.5774,  0.1177, -0.5127],
       [-0.6998, -0.0566, -0.6853,  0.1558,  0.1152],
       [ 0.1449, -0.0407, -0.3903, -0.5417, -0.7291],
       [ 0.2269,  0.4876, -0.1798,  0.7117, -0.4146],
       [-0.2445,  0.8635,  0.1109, -0.4024,  0.1428]])

Visualizamos R.

In [5]:
np.round(R,4)

array([[ 6.8308, -1.296 ,  0.5444],
       [ 0.    ,  5.9562, -2.6987],
       [-0.    , -0.    ,  7.6055],
       [ 0.    ,  0.    ,  0.    ],
       [-0.    , -0.    , -0.    ]])

Calcularemos la multiplicación de las matrices Q y R para validar que obtenemos A.

In [6]:
print('Q@R:')
pprint.pprint(Q@R)
print('A:')
pprint.pprint(A)

Q@R:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])
A:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])


### Implementación Numpy

Obtenemos Q y R con la función *numpy.linalg.qr()*

In [7]:
Q_np, R_np = np.linalg.qr(A)
print('Q_np:')
pprint.pprint(Q_np)
print('R_np:')
pprint.pprint(R_np)

Q_np:
array([[-0.61486163, -0.10860715,  0.57742769],
       [-0.69977109, -0.05656825, -0.68526264],
       [ 0.14493167, -0.04065727, -0.39032723],
       [ 0.22691322,  0.48757435, -0.17982983],
       [-0.24448069,  0.86349451,  0.11089756]])
R_np:
array([[ 6.83080522, -1.29604047,  0.54435749],
       [ 0.        ,  5.9561967 , -2.69873402],
       [ 0.        ,  0.        ,  7.6054592 ]])


Calcularemos la multiplicación de las matrices Q y R para validar que obtenemos A.

In [8]:
print('Q_np@R_np:')
pprint.pprint(Q_np@R_np)
print('A:')
pprint.pprint(A)

Q_np@R_np:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])
A:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])


### Comparación

**Validación A = QR**

Valores obtenidos con la función implementada por los programadores.

In [9]:
print('Q@R:')
pprint.pprint(Q@R)
print('A:')
pprint.pprint(A)

Q@R:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])
A:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])


Valores obtenidos con la función de numpy.

In [10]:
print('Q_np@R_np:')
pprint.pprint(Q_np@R_np)
print('A:')
pprint.pprint(A)

Q_np@R_np:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])
A:
array([[-4.2 ,  0.15,  4.35],
       [-4.78,  0.57, -5.44],
       [ 0.99, -0.43, -2.78],
       [ 1.55,  2.61, -2.56],
       [-1.67,  5.46, -1.62]])


Las dos funciones cumplen que A = QR.

Podemos ver que obtenemos los mismos resultados al multiplicar las matrices Q y R obtenidas por cada función respectivamente.

**Validación Q**

Valores obtenidos con la función implementada por los programadores.

In [11]:
print('Q:')
pprint.pprint(Q)

Q:
array([[-0.61486163, -0.10860715,  0.57742769,  0.11765035, -0.51272344],
       [-0.69977109, -0.05656825, -0.68526264,  0.15579885,  0.11516203],
       [ 0.14493167, -0.04065727, -0.39032723, -0.54169732, -0.72907507],
       [ 0.22691322,  0.48757435, -0.17982983,  0.7117186 , -0.41460766],
       [-0.24448069,  0.86349451,  0.11089756, -0.40237514,  0.14283697]])


Valores obtenidos con la función de numpy.

In [12]:
print('Q_np:')
pprint.pprint(Q_np)

Q_np:
array([[-0.61486163, -0.10860715,  0.57742769],
       [-0.69977109, -0.05656825, -0.68526264],
       [ 0.14493167, -0.04065727, -0.39032723],
       [ 0.22691322,  0.48757435, -0.17982983],
       [-0.24448069,  0.86349451,  0.11089756]])


**Validación R**

Valores obtenidos con la función implementada por los programadores.

In [13]:
print('R:')
pprint.pprint(R)

R:
array([[ 6.83080522e+00, -1.29604047e+00,  5.44357492e-01],
       [ 6.23432724e-17,  5.95619670e+00, -2.69873402e+00],
       [-2.25448082e-16, -8.05517528e-17,  7.60545920e+00],
       [ 2.24700516e-16,  4.92810237e-17,  7.94325854e-16],
       [-1.40857430e-16, -5.26886249e-17, -1.20910315e-16]])


Valores obtenidos con la función de numpy.

In [14]:
print('R_np:')
pprint.pprint(R_np)

R_np:
array([[ 6.83080522, -1.29604047,  0.54435749],
       [ 0.        ,  5.9561967 , -2.69873402],
       [ 0.        ,  0.        ,  7.6054592 ]])


Tanto las funciones implementadas por los programadores para obtener la factorización $QR$ de una matriz, como la función *linalg.qr* de la librería numpy consideran una matriz de entrada A de dimensiones $mxn$. Como resultado se obtienen las siguientes dos matrices:

+ Función implementa por los programadores:
    + matriz ortogonal $Q$ de dimensiones $mxm$
    + matriz triangular superior $R$ de dimensiones $mxn$

+ Función linalg.qr de numpy
    + matriz con columnas ortonormales $Q$ de dimensiones $mxn$
    + matriz traingular superior $R$ con dimensiones $nxn$
    
 
En el caso de la función implementada en numpy, se obtiene lo que se conoce como "Factorización thin QR", en donde $Q$ ya no es una matriz ortogonal, si no una matriz con entradas ortonormales.

Lo anterior muestra por qué en las secciones de **Validación Q** y **Validación R** se obtienen matrices distintas; sin embargo, como se demuestra en la sección **Comparación A=QR**, al multiplicar uno u otro par de matrices $QR$, se recupera la matriz original $A$.

## EJEMPLO 2 - Matriz de dimensión 3x5 (Columnas > Filas)

En este caso consideramos una matriz con las dimensiones invertidas con respecto al Ejemplo 1, es decir, el número de columnas es mayor al número de filas.

In [5]:
# Generación de matriz aleatorio de tamaño 3x5
m=3
n=5
A=np.round(fqr.crear_matriz_aleatoria(m,n,6,-6,False),2)
A

array([[ 0.82,  2.48, -1.5 ,  2.4 , -2.2 ],
       [ 4.34,  5.38, -3.54,  4.34, -5.46],
       [ 3.27, -4.45,  4.57,  0.35, -0.02]])

### Implementación programadores

De igual forma que en el ejemplo anterior, utilizamos la función **matriz_Q_R** para obtener las matrices **Q** y **R**, resultantes de la factorización de la matriz inicial $A$.

In [7]:
Q,R = fqr.matriz_Q_R(A)

SystemExit: El numero de renglones de A tiene que ser igual o mayor al no. de columnas

/home/lauragmz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3333: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


Debido a que la factorización $QR$ únicamente puede aplicarse a matrices de dimensiones $mxn$, tal que $m \leq n$; y la matriz inicial $A$, no cumple esta condición, el mensaje de error que muestra la función es correcto. 

De esta forma se valida la sugerencia propuesta en la revisión anterior "prueba_precision_factorizacion_QR", en donde era claro para el usuario la razón por la cual este tipo de matrices presentaban un error.

## Resumen de Hallazgos

En esta segunda iteración de validaciones para el caso de una matriz de $5x3$ (donde el número de filas es mayor al de columnas) queda confirmado que las funciones para la factorización $Q$R se encuentran funcionando correctamente considerando los resultados obtenidos en este análisis. Al comparar numpy vs la implementación por parte de los programadores validamos que se cumple que $A = QR$.

Las diferencias entre $Q$ y $R$ que también se identificaron en la primera iteración de validaciones se explican en la parte de arriba y son debidas a la "factorización thin QR" utilizada por numpy.

Con respecto a la matriz de tamaño $3x5$ (donde el número de columnas es mayor al número de filas),, a la cual no es posible aplicarle la factorización $QR$, queda validado que el mensaje de error desplegado al correr dicha función es informativo para el usuario.

Además, quisiera mencionar que no se presentó ningun problema al utilizar el módulo de funciones .py que recientemente se implementó por parte del equipo de programación. 