# Prueba Precisión - Factorización QR (Revisión 2)

Importamos la librerías necesarias.

In [1]:
#paquetes python
import os
import numpy as np
import copy
import pprint
from math import sqrt
from scipy.linalg import solve_triangular
import inspect
import sys

# paquetes funciones definidas obtenidas de archivos .py
import funciones_factorizacion_QR as fqr

## EJEMPLO 1 - Matriz de dimensión 5x3 (Filas > Columnas)

Verificaremos que la factorización QR de una matriz obtenida con la función de numpy, es igual a la obtenida con la función implementada por los programadores.

Empezaremos por generar una matriz aleatoria con la función crea_matriz

In [2]:
# Generamos una matriz aleatoria de tamaño definido (renglones y columnas) y valores aleatorios comprendidos en un rango, pudiendo ser sus entradas de tipo enteros o dobles
m=5
n=3
A=np.round(fqr.crear_matriz_aleatoria(m,n,6,-6,False),2)
A

array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])

### Implementación programadores

Primero, utilizaremos la función matriz_auxiliar_Arv para obtener la matriz auxiliar Arv.

In [3]:
Arv = fqr.matriz_auxiliar_Arv(A)
np.round(Arv,4)

array([[ 9.7419, -2.7161, -3.3432],
       [-0.4924,  3.8351, -0.6815],
       [ 0.178 , -0.6189,  7.3241],
       [ 0.4325, -0.4641,  1.593 ],
       [ 0.3993,  0.2307,  0.0343]])

Utilizamos la función matriz_Q para obetener Q.

In [4]:
Q = fqr.matriz_Q(Arv)
np.round(Q,4)

array([[-0.234 , -0.4552,  0.2413, -0.354 , -0.7446],
       [ 0.6077,  0.0132, -0.2935, -0.7357,  0.0556],
       [-0.2197,  0.6684,  0.5859, -0.4001,  0.0405],
       [-0.5338,  0.3651, -0.7149, -0.165 , -0.2086],
       [-0.4927, -0.4611,  0.0367, -0.3822,  0.6303]])

Utilizamos la función matriz_R para obetener R.

In [5]:
R = fqr.matriz_R(Arv)
np.round(R,4)

array([[ 9.7419, -2.7161, -3.3432],
       [ 0.    ,  3.8351, -0.6815],
       [ 0.    ,  0.    ,  7.3241],
       [ 0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ]])

Calcularemos la multiplicación de las matrices Q y R para validar que obtenemos A.

In [6]:
print('Q@R:')
pprint.pprint(Q@R)
print('A:')
pprint.pprint(A)

Q@R:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])
A:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])


### Implementación Numpy

Obtenemos Q y R con la función *numpy.linalg.qr()*

In [7]:
Q_np, R_np = np.linalg.qr(A)
print('Q_np:')
pprint.pprint(Q_np)
print('R_np:')
pprint.pprint(R_np)

Q_np:
array([[-0.23404085, -0.45518086, -0.24130459],
       [ 0.60768502,  0.01317088,  0.29347003],
       [-0.21966992,  0.66839287, -0.58589391],
       [-0.53377738,  0.36510686,  0.71486489],
       [-0.49271759, -0.46106927, -0.03665988]])
R_np:
array([[ 9.74188893, -2.71606463, -3.34323253],
       [ 0.        ,  3.83511315, -0.68152765],
       [ 0.        ,  0.        , -7.32405737]])


Calcularemos la multiplicación de las matrices Q y R para validar que obtenemos A.

In [8]:
print('Q_np@R_np:')
pprint.pprint(Q_np@R_np)
print('A:')
pprint.pprint(A)

Q_np@R_np:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])
A:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])


### Comparación

**Validación A = QR**

Valores obtenidos con la función implementada por los programadores.

In [9]:
print('Q@R:')
pprint.pprint(Q@R)
print('A:')
pprint.pprint(A)

Q@R:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])
A:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])


Valores obtenidos con la función de numpy.

In [10]:
print('Q_np@R_np:')
pprint.pprint(Q_np@R_np)
print('A:')
pprint.pprint(A)

Q_np@R_np:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])
A:
array([[-2.28, -1.11,  2.86],
       [ 5.92, -1.6 , -4.19],
       [-2.14,  3.16,  4.57],
       [-5.2 ,  2.85, -3.7 ],
       [-4.8 , -0.43,  2.23]])


Las dos funciones cumplen que A = QR.

Podemos ver que obtenemos los mismos resultados al multiplicar las matrices Q y R obtenidas por cada función respectivamente.

**Validación Q**

Valores obtenidos con la función implementada por los programadores.

In [11]:
print('Q:')
pprint.pprint(Q)

Q:
array([[-0.23404085, -0.45518086,  0.24130459, -0.35400715, -0.74463837],
       [ 0.60768502,  0.01317088, -0.29347003, -0.73574845,  0.05563276],
       [-0.21966992,  0.66839287,  0.58589391, -0.40010089,  0.04054258],
       [-0.53377738,  0.36510686, -0.71486489, -0.16496906, -0.20864341],
       [-0.49271759, -0.46106927,  0.03665988, -0.38217489,  0.6302721 ]])


Valores obtenidos con la función de numpy.

In [12]:
print('Q_np:')
pprint.pprint(Q_np)

Q_np:
array([[-0.23404085, -0.45518086, -0.24130459],
       [ 0.60768502,  0.01317088,  0.29347003],
       [-0.21966992,  0.66839287, -0.58589391],
       [-0.53377738,  0.36510686,  0.71486489],
       [-0.49271759, -0.46106927, -0.03665988]])


**Validación R**

Valores obtenidos con la función implementada por los programadores.

In [13]:
print('R:')
pprint.pprint(R)

R:
array([[ 9.74188893, -2.71606463, -3.34323253],
       [ 0.        ,  3.83511315, -0.68152765],
       [ 0.        ,  0.        ,  7.32405737],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])


Valores obtenidos con la función de numpy.

In [14]:
print('R_np:')
pprint.pprint(R_np)

R_np:
array([[ 9.74188893, -2.71606463, -3.34323253],
       [ 0.        ,  3.83511315, -0.68152765],
       [ 0.        ,  0.        , -7.32405737]])


Tanto las funciones implementadas por los programadores para obtener la factorización $QR$ de una matriz, como la función *linalg.qr* de la librería numpy consideran una matriz de entrada A de dimensiones $mxn$. Como resultado se obtienen las siguientes dos matrices:

+ Función implementa por los programadores:
    + matriz ortogonal $Q$ de dimensiones $mxm$
    + matriz triangular superior $R$ de dimensiones $mxn$

+ Función linalg.qr de numpy
    + matriz con columnas ortonormales $Q$ de dimensiones $mxn$
    + matriz traingular superior $R$ con dimensiones $nxn$
    
 
En el caso de la función implementada en numpy, se obtiene lo que se conoce como "Factorización thin QR", en donde $Q$ ya no es una matriz ortogonal, si no una matriz con entradas ortonormales.

Lo anterior muestra por qué en las secciones de **Validación Q** y **Validación R** se obtienen matrices distintas; sin embargo, como se demuestra en la sección **Comparación A=QR**, al multiplicar uno u otro par de matrices $QR$, se recupera la matriz original $A$.

## Resumen de Hallazgos

En esta segunda iteración de validaciones para el caso de una matriz de 5x3 (donde el número de filas es mayor al de columnas) queda confirmado que las funciones para la factorización QR se encuentran funcionando correctamente considerando los resultados obtenidos en este análisis. Al comparar numpy vs la implementación por parte de los programadores validamos que se cumple que A = QR.

La diferencias entre Q y R que también se identificaron en la primera iteración de validaciones se explican en la parte de arriba.

Además, quisiera mencionar que no se presentó ningun problema al utilizar el modulo de funciones py que recientemente se implementó por parte del equipo de programación. 