# Prueba Unitaria

## Eliminación por bloques con QR considerando sistemas con soluciones infinitas

La intención de esta segunda revisión consiste en validar las funciones implementadas por los programadores para resolver sistemas de ecuaciones lineales por bloques, en el módulo **funciones_factorizacion-QR**. Particularmente este notebook busca identificar los mensajes de error emitidos por el algoritmo, cuando se enfrenta a sistemas de ecuaciones con soluciones infinitas.

Las funciones que serán utilizadas, sufrieron modificaciones con respecto a las usadas en la primera revisión (archivo *pu_epbQR_sistema_soluciones_infinitas*).

In [1]:
#Librerías python
import numpy as np
import pprint

# Módulo que incluye funciones para resolver SEL por bloques con apoyo de QR
import funciones_factorizacion_QR as fqr

### Ejemplo 1 - Matriz 2 x 2 (Ecuaciones linealmente dependientes)

El siguiente sistema representa un sistema de 2 ecuaciones con 2 incógnitas. La segunda ecuación es una combinación lineal de la primera, por lo que al multiplicar la segunda ecuación por -2 se obtiene la primera. Esto conduce a tener un sistema de una ecuación con dos incógnitas; y debido a los coeficientes involucrados, el sistema tiene soluciones infinitas.

In [2]:
# Generación de lado izquierdo A y lado derecho b de un sistema de ecuaciones de 2x2

A = np.array([[-6, 4], [3, -2]], dtype='d')
b = np.array([[2], [-1]], dtype='d')
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[-6.,  4.],
       [ 3., -2.]])
b:
array([[ 2.],
       [-1.]])


**Numpy**

Puesto que el sistema tiene infinitas soluciones, se utilizará de la función *linalg.solve(A,b)*, perteneciente a la librería numpy para conocer el error que marca al ingresar tal sistema. 

In [3]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

Puntualmente, el error indicado por la función *linalg.solve* indica que la matriz A es singular, lo que implica que no sea posible obtener la matriz inversa y por tanto no se puede resolver el sistema.

**Implementación Programadores - Eliminación por bloques con QR**

La función *eliminacion_bloques*, implementada por los programadores permite resolver un sistema de ecuaciones lineales. Se revisará el error que despliega al intentar resovler el sistema de ecuaciones propuesto.

In [4]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

/home/lauragmz/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3333: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


Lo anterior demuestra que la función programada está preparada para recibir un sistema con soluciones infinitas y ante esta situación, despliega un mensaje indicando que la matriz $A$ debe ser no singular, es decir, debe ser una matriz cuadrada con determinante distinto de cero.

Comparando con la primera prueba que se realizó (archivo *pu_epbQR_sistema_soluciones_infinitas.ipynb*), se observa una mejora en el mensaje de error mostrado. En esta ocasión el usuario visualiza un mensaje directo sobre es el incoveniente presentado al intentar resolver el sistema. 

El error que marca esta función es consistente con el desplegado por la función *linalg.solve*.

### Ejemplo 2 - Matriz $10^{2}$ x $10^{2}$ (Matriz de unos, sistema no homogéneo)

Se genera un sistema de ecuaciones lineales de $10^{2} x 10^{2}$, cuyo lado izquierdo es una matriz de 1's y el lado derecho es un vector que contiene al número 100 en cada una de sus entradas. Este sistema representa la misma ecuación, repetida 100 veces.

In [5]:
# Generación lado izquierdo A (matriz de 1's) y lado derecho b (vector con entradas igual a 100)

m = 10**2
n = 10**2
A = fqr.crear_matriz_aleatoria(m, n, 1, 1,True)
b = fqr.crear_matriz_aleatoria(m, 1, 100, 100,True)
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b[0:10,:])

A:
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
b:
array([[100.],
       [100.],
       [100.],
       [100.],
       [100.],
       [100.],
       [100.],
       [100.],
       [100.],
       [100.]])


**Numpy**

Nuevamente se hará uso de la función *linalg.solve(A,b)* de la librería numpy para conocer qué error despliega al intentar resolver el sistema propuesto.

In [6]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

De igual forma que en el Ejemplo 1, el error indica que la matriz A es singular.

**Implementación Programadores - Eliminación por bloques con QR**

Se implementa la función *eliminacion_bloques* creada por los programadores para verificar que se obtenga el mismo error que marca al función *linalg.solve(A,b)*.

In [7]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

Efectivamente, la función *eliminacion_bloques* indica que la matriz A deber ser no singular, lo cual como se explica en el Ejemplo 1, es consistente con el errir desplegado por numpy.

### Ejemplo 3 - Matriz $10^{2}$ x $10^{2}$ (Matriz de unos, sistema homogéneo)

De forma análoga al Ejemplo 2, se genera un sistema de ecuaciones lineales de $10^{2} x 10^{2}$, cuyo lado izquierdo es una matriz de 1's; sin embargo el lado derecho es un vector que contiene al número 0 en cada una de sus entradas, es decir, se trata de un sistema homogéneo. De igual forma, este sistema representa la misma ecuación, repetida 100 veces.

In [8]:
# Generación lado izquierdo A (matriz de 1's) y lado derecho b (vector con entradas igual a 0)

m = 10**2
n = 10**2
A = fqr.crear_matriz_aleatoria(m, n, 1, 1,True)
b = fqr.crear_matriz_aleatoria(m, 1, 0, 0,True)
print("A:")
pprint.pprint(A)
print("b:")
# se muestran los primeros 10 elementos del lado derecho b
pprint.pprint(b[0:10,:]) 

A:
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
b:
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])


**Numpy**

Se intenta resolver el sistema con *linalg.solve(A,b)*:

In [9]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

*linalg.solve(A,b)* despliega el mismo error que en los Ejemplos 1 y 2.

**Implementación Programadores - Eliminación por bloques con QR**

Finalmente se ejecuta la función *eliminacion_bloques* implementada por los programadores.

In [10]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

Tal como se esperaba, *eliminacion_bloques* indica que A debe ser una matriz no singular.

## Resumen de Hallazgos

Los ejemplos anteriores muestran evidencia de que la función **eliminacion_bloques** está preparada para recibir un sistema de ecuaciones con soluciones infinitas y desplegar un mensaje de error. 

Los Ejemplos 2 y 3 demuestran que la solución de un sistema de ecuaciones es independiente del lado derecho $b$. En éstos se mantuvo el mismo lado izquierdo $A$ y se varió el lado derecho $b$, de forma que el Ejemplo 3 es un sistema homogéneo y el Ejemplo 2 no lo es. En ambos casos el error asociado indica que la matriz $A$ deber ser no singular. Por lo tanto la solución del sistema de ecuaciones depende en su totalidad del lado izquierdo $A$.