# Prueba Unitaria (Revisión 2)

## Eliminación por bloques con QR considerando sistemas sin solución

In [1]:
#paquetes python
import os
import numpy as np
import copy
import pprint
from math import sqrt
from scipy.linalg import solve_triangular
import inspect
import sys

# paquetes funciones definidas obtenidas de archivos .py
import funciones_factorizacion_QR as fqr

### Ejemplo 1 - Matriz 3 x 3 (Fila con ceros)

Empezaremos por generar un sistema de ecuaciones lineales sin solución.

In [2]:
# Generamos una matriz 3 x 3
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]], dtype='d')
b = np.array([[-2], [0], [5]], dtype='d')
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])
b:
array([[-2.],
       [ 0.],
       [ 5.]])


**Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)*  para validar que el sistema de ecuaciones efectivamente no tiene solución.

In [3]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

Podemos observar que la función de numpy nos arroja un error al tratar de resolver un sistema de ecuaciones lineales sin solución.

El error se refiere a que la matriz A es una matriz singular.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para validar sus funcionalidad cuando trata de resolver un sistema de ecuaciones lineales sin solución.

In [4]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


Podemos observar que ahora la función nos arroja un mensaje explicando que la matriz A debe ser no singular.

### Ejemplo 2 - Matriz 10^2 x 10^2 (Fila con ceros)

Empezamos por generar un sistema de ecuaciones lineales de 10^2 x 10^2

In [5]:
m = 100
n = 100
A = np.round(fqr.crear_matriz_aleatoria(m, n, 10, -10,False), 2)
b = np.round(fqr.crear_matriz_aleatoria(m, 1, 10, -10,False), 2)
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[ 4.89, -6.71,  4.82, ..., -1.22,  1.31, -0.13],
       [ 0.72, -4.82,  1.48, ...,  7.89,  3.48, -4.58],
       [-6.73, -7.99, -6.97, ...,  6.4 ,  5.55, -8.27],
       ...,
       [-4.63, -7.57, -7.48, ...,  8.14,  4.7 ,  8.27],
       [-8.78,  9.7 , -8.98, ..., -8.53, -5.08,  2.41],
       [ 2.54,  1.39,  1.88, ..., -6.98,  3.56, -1.57]])
b:
array([[ 2.76],
       [ 2.76],
       [ 3.85],
       [ 5.54],
       [-5.57],
       [ 1.29],
       [ 5.87],
       [-0.65],
       [ 1.26],
       [-1.89],
       [ 9.  ],
       [-0.45],
       [ 8.74],
       [ 4.61],
       [-1.88],
       [-3.11],
       [ 7.11],
       [-6.47],
       [-4.2 ],
       [-5.17],
       [-0.67],
       [ 6.68],
       [ 9.2 ],
       [ 2.67],
       [ 2.87],
       [ 6.2 ],
       [ 2.42],
       [-5.7 ],
       [-8.54],
       [ 1.21],
       [ 1.23],
       [ 4.1 ],
       [-4.41],
       [-4.6 ],
       [-4.49],
       [-9.39],
       [ 1.92],
       [ 9.39],
       [ 8.57],
       [-0.63],
     

Actualizaremos la ultima fila de la matriz con puros ceros para volverlo un sistema de ecuaciones lineales sin solución.

In [6]:
A[-1] = np.zeros(n)

In [7]:
print("A:")
pprint.pprint(A)

A:
array([[ 4.89, -6.71,  4.82, ..., -1.22,  1.31, -0.13],
       [ 0.72, -4.82,  1.48, ...,  7.89,  3.48, -4.58],
       [-6.73, -7.99, -6.97, ...,  6.4 ,  5.55, -8.27],
       ...,
       [-4.63, -7.57, -7.48, ...,  8.14,  4.7 ,  8.27],
       [-8.78,  9.7 , -8.98, ..., -8.53, -5.08,  2.41],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])


**Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)*  una vez mas para validar que el sistema de ecuaciones dado efectivamente no tiene solución.

In [8]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

Podemos observar que la función de numpy nos arroja el mismo error que en el Ejemplo 1.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para validar sus funcionalidad cuando trata de resolver un sistema de ecuaciones lineales sin solución.

In [9]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

De nuevo, podemos observar que ahora la función nos arroja un mensaje explicando que la matriz A debe ser no singular también para el caso de una matriz de 10^2 x 10^2.

### Ejemplo 3 - Matriz 2 x 2 (Sistema incompatible - Rectas Paralelas)

Empezaremos por generar un sistema de ecuaciones lineales sin solución (Rectas Paralelas).

In [10]:
# Generamos una matriz 2 x 2 incompatible
A = np.array([[11, 4], [132, 48]], dtype='d')
b = np.array([[7], [-1]], dtype='d')
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[ 11.,   4.],
       [132.,  48.]])
b:
array([[ 7.],
       [-1.]])


**Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)*  una vez mas para validar que el sistema de ecuaciones dado efectivamente no tiene solución.

In [11]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

Podemos observar que la función de numpy nos arroja el mismo error que en el Ejemplo 1 y 2.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para validar sus funcionalidad cuando trata de resolver un sistema de ecuaciones lineales sin solución (Rectas paralelas).

In [12]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser no singular

Identificamos para este caso que la función nos arroja un mensaje explicando que la matriz A debe ser no singular, al igual que en los ejemplos anteriores.

### Ejemplo 4 - Matriz 4 x 3 no cuadrada

In [13]:
m = 4
n = 3
A = np.round(fqr.crear_matriz_aleatoria(m, n, 10, -10,False), 2)
b = np.round(fqr.crear_matriz_aleatoria(m, 1, 10, -10,False), 2)
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[-0.2 , -3.53,  4.31],
       [-2.66,  7.57, -8.66],
       [ 9.19,  0.56,  8.08],
       [ 7.17,  6.05, -8.48]])
b:
array([[-1.27],
       [ 5.77],
       [ 2.74],
       [-8.43]])


**Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)* para observar que hace cuando se enfrenta a una matriz no cuadrada.

In [14]:
np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

La función nos arroja un error en el que nos dice que las dimensiones de la matriz deben de ser cuadradas.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para observar que hace cuando se enfrenta a una matriz que no es cuadrada.

In [15]:
fqr.eliminacion_bloques(A,b)

SystemExit: A debe ser cuadrada

Observamos que ahora la función nos arroja un mensaje explicando que la matriz A debe ser cuadrada.

## Resumen de Hallazgos

En esta prueba confirmamos que los issues levantados en la iteración previa de validaciones han sido atendidos satisfactoriamente por el equipo de programación. Ahora la función es capaz de identificar cuando se enfrenta a un sistema de ecuaciones lineales sin solución y mandar un mensaje acorde, los mismo para el caso cuando se enfrenta a una matriz no cuadrada.

Dados estos hallazgos, procederemos a cerrar el issue asociado.