### Cargar las librerías

In [1]:
import os
import numpy as np
import pprint
import copy
from math import sqrt
from scipy.linalg import solve_triangular

### Cargar las funciones

In [2]:
%run -i funciones_factorizacion_QR.py

# Prueba Unitaria

## Eliminación por bloques con QR considerando sistemas con única solución

### Ejemplo 1 - Matriz 2 x 2

Empezaremos por generar un sistema de ecuaciones lineales con solución unica.

In [3]:
# Generamos una matriz 2 x 2
A = np.array([[2, 3], [3, -1]], dtype='d')
b = np.array([[1], [-1]], dtype='d')
print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[ 2.,  3.],
       [ 3., -1.]])
b:
array([[ 1.],
       [-1.]])


Calculamos el determinante de la matriz A

In [4]:
np.linalg.det(A)

-11.000000000000002

Dado que el determinante de la matriz es distinto de cero la matriz A tiene solución única

**Solución del sistema usando Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)*  para validar que el sistema de ecuaciones efectivamente no tiene solución.

In [5]:
np.linalg.solve(A,b)

array([[-0.18181818],
       [ 0.45454545]])

Podemos observar que la función de numpy nos arroja la solución al sistema de ecuaciones lineales propuesto.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para validar sus funcionalidad cuando trata de resolver un sistema de ecuaciones lineales con solución única.

In [6]:
eliminacion_bloques(A,b)

array([[-0.18181818],
       [ 0.45454545]])

Podemos observar que la función nos arroja la misma solución que numpy.

### Ejemplo 2 - Matriz 10^2 x 10^2

Generaremos un sistema de ecuaciones lineales de 10^2 x 10^2

Fijamos una semilla para que el ejemplo sea replicable

In [7]:
np.random.seed(2020)

In [8]:
m = 100
n = 100
A = crear_matriz_aleatoria(m, n, 5, -5,True)

# sumamos las entradas de las filas para crear el vector b, así nuestro vector x tendrá por solución el valor de 1 en cada entrada.
b = np.sum(A, axis=1)

print("A:")
pprint.pprint(A)
print("b:")
pprint.pprint(b)

A:
array([[ 5.,  4.,  0., ..., -1., -4.,  0.],
       [-3.,  5., -2., ...,  3., -3., -1.],
       [-4., -5., -3., ..., -1., -5.,  3.],
       ...,
       [-1., -5., -5., ..., -1., -5., -2.],
       [-2.,  1., -3., ...,  5.,  4.,  3.],
       [ 3.,  4.,  1., ..., -1.,  3.,  5.]])
b:
array([  7.,   3., -37., -19., -21.,  33., -21.,  -4., -36.,   4.,  13.,
       -74.,  -4., -31.,  21.,   7.,  13.,  -6.,  13.,  10., -58.,  17.,
       -50.,  25., -19.,  15., -35.,   4.,  -2.,   6., -26., -15., -65.,
       -17.,  75., -22.,  22., -30.,  39.,  39., -67.,  24., -51.,  29.,
        -3., -24.,   1.,   8.,  34.,  19.,  13.,  24.,  27., -12.,   9.,
       -17., -15., -19.,  25., -31.,  24.,  34.,  19., -25., -42., -13.,
       -31., -56., -33.,  11., -19., -48.,  80., -11., -11.,   7., -22.,
         2.,  41., -18., -32.,  79., -16.,  29., -36., -31., -15.,  31.,
       -31.,  -7.,  34.,  20., -11.,  -2., -16., -10., -47., -28., -78.,
        11.])


Calculamos el determinante

In [16]:
np.linalg.det(A)

-4.212288088814109e+127

El determinante es cercano a cero, pero no es cero.

**Solución del sistema usando Numpy**

Utilizaremos la función de numpy *np.linalg.solve(A,b)*  una vez mas para validar que el sistema de ecuaciones dado tiene solución.

In [9]:
np.linalg.solve(A,b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Podemos observar que la función de numpy nos arroja la solución que esperabamos.

**Implementación Programadores - Eliminación por bloques con QR**

Utilizaremos la función eliminacion_bloques implementada por los programadores para validar su funcionalidad cuando trata de resolver un sistema de ecuaciones lineales de 10^2x100^2.

In [10]:
eliminacion_bloques(A,b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Podemos observar que la función nos arroja el mismo resultado.

## Resumen

La función eliminacion_bloques(A,b) es capaz de resolver efectivamente sistemas de ecuaciones con solución única. 