In [1]:
#paquetes python
import os
import numpy as np
import copy
import pprint
from math import sqrt
from scipy.linalg import solve_triangular
import inspect
import sys

#paquetes funciones definidas obtenidas de archivos .py
import funciones_factorizacion_QR as fQR

## Prueba solución incorrecta

In [2]:
#Generamos un sistema de ecuaciones lineales
m=4
n=4
A=np.round(fQR.crear_matriz_aleatoria(m,n,6,-6,False),2)
b = np.round(fQR.crear_matriz_aleatoria(m,1,6,-6,False),2)
print("A:",A)
print("b:",b)

A: [[-2.83 -4.87  4.23  4.65]
 [-4.34  2.31  3.92  3.16]
 [-1.39 -2.07 -1.42  2.06]
 [ 2.19 -5.87  0.26 -5.93]]
b: [[-3.56]
 [-1.5 ]
 [ 0.69]
 [ 5.09]]


In [3]:
np.linalg.solve(A,b)

array([[-1.15384111],
       [-0.21244429],
       [-0.64617361],
       [-1.10250745]])

In [4]:
fQR.Solucion_SEL_QR_nxn(A,b)

array([[-1.15384111],
       [-0.21244429],
       [-0.64617361],
       [-1.10250745]])

In [5]:
fQR.eliminacion_bloques(A,b)

array([[-1.15384111],
       [-0.21244429],
       [-0.64617361],
       [-1.10250745]])

## Prueba solución correcta

In [10]:
#Generamos un sistema de ecuaciones lineales
m=10
n=10
A=np.round(fQR.crear_matriz_aleatoria(m,n,6,-6,False),2)
b = np.round(fQR.crear_matriz_aleatoria(m,1,6,-6,False),2)
print("A:",A)
print("b:",b)

A: [[ 1.49 -0.86 -1.35  4.76  2.77  4.93 -3.34 -2.23  2.61  4.92]
 [ 5.12  2.82 -3.8  -2.81  0.42 -1.92 -0.11  2.1  -1.1   5.22]
 [-5.58  1.42 -4.57  0.18 -1.63 -3.19  2.93  1.91 -5.37 -3.27]
 [-5.06 -4.44  0.01  1.72 -3.99 -5.73  2.61  1.59 -3.15  0.08]
 [ 5.21  1.13  1.85  0.1   0.69  3.52 -1.16  2.46  0.4  -5.41]
 [-4.56 -5.67 -1.72 -2.52  3.11  1.62  1.47  1.45  1.48  1.1 ]
 [-0.03  5.62 -1.66  4.61 -1.34  1.36 -2.7   4.71  5.82  4.71]
 [-4.23 -5.88  1.88 -4.32  5.25  4.26 -0.44 -2.36  1.24  4.81]
 [-1.11 -5.65 -0.91 -2.89 -2.47 -0.93 -3.13 -1.75  0.32 -5.79]
 [ 1.05 -0.9   4.2  -1.36 -4.36 -2.53  2.75 -5.6  -4.95 -3.46]]
b: [[-0.1 ]
 [ 0.63]
 [-4.01]
 [-5.23]
 [ 2.5 ]
 [ 2.41]
 [ 3.36]
 [ 3.91]
 [ 0.58]
 [ 1.9 ]]


In [11]:
np.linalg.solve(A,b)

array([[ 0.05063153],
       [ 0.06250187],
       [-0.1950796 ],
       [-0.97640005],
       [-1.70848854],
       [ 1.81391474],
       [ 0.92209403],
       [-0.00584456],
       [ 0.59082345],
       [ 0.32057775]])

In [12]:
fQR.Solucion_SEL_QR_nxn(A,b)

array([[ 0.05063153],
       [ 0.06250187],
       [-0.1950796 ],
       [-0.97640005],
       [-1.70848854],
       [ 1.81391474],
       [ 0.92209403],
       [-0.00584456],
       [ 0.59082345],
       [ 0.32057775]])

In [13]:
fQR.eliminacion_bloques(A,b)

array([[ 0.05063153],
       [ 0.06250187],
       [-0.1950796 ],
       [-0.97640005],
       [-1.70848854],
       [ 1.81391474],
       [ 0.92209403],
       [-0.00584456],
       [ 0.59082345],
       [ 0.32057775]])

Prueba 10x10

In [10]:
#Generamos un sistema de ecuaciones lineales
m=1000
n=1000
A=np.round(fQR.crear_matriz_aleatoria(m,n,10,-10,False),2)
b = np.round(fQR.crear_matriz_aleatoria(m,1,10,-10,False),2)
#print("A:",A)
#print("b:",b)

In [11]:
x1=np.linalg.solve(A,b)

In [ ]:
x2=fQR.eliminacion_bloques(A,b)

In [8]:
np.mean(A)

-0.0006959999999999997

In [ ]:
2